In [2]:
import pandas as pd
import numpy as np

In [29]:
data = pd.read_csv("csv/dataset_sms_spam _v1.csv")
data.head()

Teks  label
0  [PROMO] Beli paket Flash mulai 1GB di MY TELKO...      2
1  2.5 GB/30 hari hanya Rp 35 Ribu Spesial buat A...      2
2  2016-07-08 11:47:11.Plg Yth, sisa kuota Flash ...      2
3  2016-08-07 11:29:47.Plg Yth, sisa kuota Flash ...      2
4  4.5GB/30 hari hanya Rp 55 Ribu Spesial buat an...      2

In [33]:
data[data['label']==1]

Teks  label
239  Jika anda bermasalah dgn CC/KT@, stres dgn bun...      1
240  Lelah byr min payment? Kami Solusinya, bantu s...      1
241  Dana Tunai (KTA) bunga 0,99% hingga 300 jt. Sy...      1
242  “ROXI CELL” Hanya dengan Rp.100rb Anda bisa ja...      1
243  3 RAMADHAN Selamat Anda Pemenang Rp.100jt. PIN...      1
244  Anda brminat cash&kredit mtor scond brg istmwa...      1
245  ANDA MAU MENANG TOGEL 100% Tembus pasang shio ...      1
246  Anda mempunyai 3 pesan suara dari 083139195872...      1
247  Anda pmain togel sring kalah.mau bagi hasil. M...      1
248  ANEKA SHOP Berbagi Promo Type Blackberry DAKOT...      1
249  Anyonghaseyo! Ngaku KPOPers Sejati?? Ayo lengk...      1
250  Artha Cell diskon Brg elektronik BB Dakota 3 j...      1
251  Ass, mengenai rumah dan tanah yg kemarin, sy s...      1
252  Ass, Sy Randy. Mengenai mobil yg sdh sy liat k...      1
253  Ass,maaf sy WAHYU.mengenai Mobil bpk yg mau di...      1
254  Ass. Maaf sy by hj.suri yang kemarin survey ru...      1
255  Ass.sy SUGIYONO yg tempo hari mngenai mobil TO...      1
256  Assalamu alaikum,saya RESKI dr Costumer Servis...      1
257  Assalamu alaiqum, nenek masuk rumah sakit tolo...      1
258  ayah isikan pulsa xl 50rb di no 0818643929 sek...      1
259  Bapak tukokno pulsa AS ndisek 20ribu iki nmrku...      1
260  BELANJA ONLINE Promo Disc 50% BB Dakota 2,8jt ...      1
261  BELANJA ONLINE TOKO RESKY DISCON 50% BB LAPTOP...      1
262  Belikan dulu mama pulsa simpati 20 ribu ini no...      1
263  Bella bingung bang mau nulis apa, daripada aq ...      1
264  berkah 1000 poin" Nomor Anda mndpt Hadiah ke-I...      1
265  Berkat isi ulang pulsa No anda T,pilih sbg pem...      1
266  Berkat isi ulang pulsa No Anda Terpilih sbg Pe...      1
267  BIG SALE !!! DISCOUND 40% Z10-4,4jt IPHONE 5 3...      1
268  BIG SALE 50% SINAR Blackberry -Z10 Rp.3,8jt -D...      1
..                                                 ...    ...
544  TOKO RAHMAT ABADI BIG SALE 50% Blackberry/Ipho...      1
545  Tolong belikan dulu mama pulsa 25rb di no AS b...      1
546  tolong uangnya di kirim ke rekening ini aja,BR...      1
547  Tolong uangnya di transfer aja kesini MANDIRI ...      1
548  Tolong uangnya di transfer saja ke Bank ----- ...      1
549  Tolong uangnya Di transfer sekarang aja ke ban...      1
550  Tolong uangnya dikirim aja kesini BANK DANAMON...      1
551  Tolong uangnya ditransfer saja ke Bank xxx A/n...      1
552  TOP100 CELLULER Discound 25% BB DACOTA RP. 3,9...      1
553  TOUR-TRAVEL dptkan tiket pesawat, promo domest...      1
554  Transfer ke Bank xxx saja a/n xxx No rek 73906...      1
555  Transfer ke BNI aja, a/n SORAYA HARUM rek;0233...      1
556  Transfer ke Mandiri aja, a/n Resti Amanda nore...      1
557  Transfer saja uangnya ke rek ini.mandiri.NO Re...      1
558  Transfernya ke BRI aja A/n ANGGA PRASTIA No Re...      1
559  Trima ksh telah mjd pelanggan kami "CNF AQUA" ...      1
560  TSELpoin 777 kejutan POIN Hadiah Rp.15jt Resmi...      1
561  Uangnya di Trnsfer di BNI ini aja a/n RASTINA ...      1
562  Uangnya dikirim aja ke Rekening ini, BankBNI a...      1
563  Uangnya dikirim saja ke Rek. BANK BNI A/n. : S...      1
564  WASSALAMU ALAIKUM WR WB UANGNYA DIKIRIM SAJA K...      1
565  Ya Allah, semoga yg mempunyai hp ini & keluarg...      1
566  Yank tlong isi’in aku pulsa 10rb, di no ini,08...      1
567  Yank Tolong isi'in pulsa di no ini.08532555674...      1
568  Yank, isikan dl pulsa di no as ini 08532304867...      1
569  Yth Bpk/Ibu. BNI menyatakan Rekening anda terp...      1
570  Yth Isti Sofiyah. Diminta Segera Hubungi Bpk D...      1
571  YTH kpd bpk/ibu sy Eka Novitasari kariyawan 3c...      1
572  YTH,MIitra Silahkan cek poin anda dan tukarkan...      1
573  Yuk Ikuti akun dakwah, caranya: ketik IKUT [sp...      1

[335 rows x 2 columns]

In [9]:
data.label.value_counts()

0    569
1    335
2    239
Name: label, dtype: int64

In [12]:
# mengubah data teks -> matriks
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer()

vect.fit(data.Teks)

X = vect.transform(data.Teks)

In [13]:
X

<1143x4951 sparse matrix of type '<class 'numpy.int64'>'
	with 19191 stored elements in Compressed Sparse Row format>

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, data.label)

In [35]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

model = MultinomialNB()

model.fit(X_train, y_train)

model2 = LinearSVC()
model2.fit(X_train, y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [38]:
y_pred = model.predict(X_test)
y_pred2 = model2.predict(X_test)

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report

print("NAIVE BAYES")
print("confusion matrix: ")
print(confusion_matrix(y_pred, y_test))
print("Accuracy Score: ")
print(accuracy_score(y_pred, y_test))
print("classification report: ")
print(classification_report(y_pred, y_test))
print()
print("LINEAR SVM")
print("confusion matrix: ")
print(confusion_matrix(y_pred2, y_test))
print("Accuracy Score: ")
print(accuracy_score(y_pred2, y_test))
print("classification report: ")
print(classification_report(y_pred2, y_test))

NAIVE BAYES
confusion matrix: 
[[145   1   0]
 [  2  82   2]
 [  4   9  41]]
Accuracy Score: 
0.9370629370629371
classification report: 
              precision    recall  f1-score   support

           0       0.96      0.99      0.98       146
           1       0.89      0.95      0.92        86
           2       0.95      0.76      0.85        54

    accuracy                           0.94       286
   macro avg       0.94      0.90      0.91       286
weighted avg       0.94      0.94      0.94       286


LINEAR SVM
confusion matrix: 
[[150   4   3]
 [  0  83   1]
 [  1   5  39]]
Accuracy Score: 
0.951048951048951
classification report: 
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       157
           1       0.90      0.99      0.94        84
           2       0.91      0.87      0.89        45

    accuracy                           0.95       286
   macro avg       0.93      0.94      0.93       286
weighted avg       0

In [42]:
sms_baru = ["halo, apa kabar?",
           "pinjaman tanpa jaminan hanya disini",
           "promo paket flash 1 GB hanya Rp. 10000",
            "titip nasi goreng 10000 , bayar pake pinjaman gopay"
           ]

# langkah 1 : ubah dari teks -> matriks
sms_baru_vec = vect.transform(sms_baru)

# langkah 2 : masukkan ke dalam model machine learning
hasil = model.predict(sms_baru_vec)

print(hasil)

[0 1 2 0]
